server:
  port: 8056

spring:
  application:
    name: producer  #微服务名称

  #配置nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848



management:
  endpoints:
    web:
      exposure:
        include: '*'
