# common spring boot settings

spring.redis.database=
spring.redis.host=127.0.0.1
spring.redis.port=6397
spring.redis.password=
spring.redis.ssl=
spring.redis.timeout=
spring.redis.cluster.nodes=
spring.redis.sentinel.master=
spring.redis.sentinel.nodes=

