spring:
  #数据源配置
  data:
    mongodb:
      # 主机地址
      host: 127.0.0.1
      # 数据库
      database: articledb
      # 默认端口是27017
      port: 27017
      # 也可以使用uri连接
      # bobo:123456 账号密码
#     uri: mongodb://bobo:123456@180.76.159.126:27017,180.76.159.126:27018,180.76.159.126:27019/articledb?connect=replicaSet&slaveOk=true&replicaSet=myrs